module.exports = [
    { name: "Qatar" },
    { name: "Ecuador" },
    { name: "Senegal" },
    { name: "Netherlands" },
    { name: "England" },
    { name: "Iran" },
    { name: "USA" },
    { name: "Wales" },
    { name: "Argentina" },
    { name: "Saudi Arabia" },
    { name: "Mexico" },
    { name: "Poland" },
    { name: "France" },
    { name: "Australia" },
    { name: "Denmark" },
    { name: "Tunisia" },
    { name: "Spain" },
    { name: "Costa Rica" },
    { name: "Germany" },
    { name: "Japan" },
    { name: "Belgium" },
    { name: "Canada" },
    { name: "Morocco" },
    { name: "Croatia" },
    { name: "Brazil" },
    { name: "Serbia" },
    { name: "Switzerland" },
    { name: "Cameroon" },
    { name: "Portugal" },
    { name: "Ghana" },
    { name: "Uruguay" },
    { name: "South Korea}" }
]